import { Inter } from "next/font/google";
import "./globals.css";
import Darkmodetoggle from "@/components/Darkmodetoggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>{children}</div>
                <div className="fixed bottom-0 dark:bg-transparent right-0 mx-3 my-4 z-50 px-12 ">
                    <Darkmodetoggle />
                </div>
            </body>
        </html>
    );
}
